name: boxbox test 배포

on:
  push:
    branches: [ beta-release ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: 코드 가져오기
        uses: actions/checkout@v4


      - name: JDK 21 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21


      - name: 빌드
        run: ./gradlew clean build -x test


      - name: JAR 파일 찾기
        id: artifact
        run: echo "jar_file=$(ls -1t build/libs/*SNAPSHOT.jar | head -n1)" >> $GITHUB_OUTPUT


      - name: 서버로 JAR 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USER }}
          key: ${{ secrets.NCP_PRIVATE_KEY }}
          source: ${{ steps.artifact.outputs.jar_file }}
          target: /root/deploy/


      - name: 서버에서 실행 교체
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USER }}
          key: ${{ secrets.NCP_PRIVATE_KEY }}
          script: |
            set -Eeuo pipefail
            APP_DIR=/root/deploy
            TARGET="$APP_DIR/boxbox-latest.jar"
            
            # 최신 JAR: 심볼릭 링크/타깃 제외, 실제 파일만
            LATEST_JAR=$(
              find "$APP_DIR" -maxdepth 1 -type f -name "*.jar" ! -path "$TARGET" \
                -printf '%T@ %p\n' | sort -nr | awk 'NR==1{print $2}'
            )
            echo "LATEST_JAR=${LATEST_JAR:-<none>}"
  
            if [[ -n "${LATEST_JAR:-}" ]]; then
              SRC_REAL="$(readlink -f "$LATEST_JAR")"
              TGT_REAL="$(readlink -f "$TARGET" 2>/dev/null || true)"
              if [[ "$SRC_REAL" != "$TGT_REAL" ]]; then
                ln -sfn "$SRC_REAL" "$TARGET"
                echo "Updated symlink: $TARGET -> $SRC_REAL"
              else
                echo "Symlink already up-to-date."
              fi
            else
              echo "No JAR found to link."
            fi
  
            sudo systemctl daemon-reload
            sudo systemctl restart boxbox.service
            sudo systemctl status boxbox.service --no-pager || true
            journalctl -u boxbox.service -n 80 --no-pager || true
